  # Jaeger : L'outil de visualisation des traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./scripts:/app/scripts
      - ./ml:/app/ml
    networks:
      - hr-pulse-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://95bacdd00740:8000/api/v1
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://95bacdd00740:8000/api/v1
    depends_on:
      - backend
    networks:
      - hr-pulse-network

networks:
  hr-pulse-network:
    driver: bridge
